### ISSUE TITLE
Design Postcard

### ISSUE THREAD

**Issue by edrushka** [mozilla/webmaker-launch#82]
Design postcard for WM launch (based on poster)

**Comment by lovegushwa** [comment]
R? @cassiemc @HPaulJohnson @edrushka  @xmatthewx @secretrobotron @KevZawacki 
Hi Everyone, Please checkout the 5x7in postcard. Same copy as the poster, but split front and back. 
I included the google play logo as per @HPaulJohnson 's request. 
- The URL will be localized. Let me know if we are good to go and I will knock out the other languages.
- The colors show are in CMYK, that's why they lack a little punch on screen.

![webmaker-postcard-5x7in](https://cloud.githubusercontent.com/assets/12228435/8466556/cc4c6e82-2008-11e5-998d-71449968630b.jpg)

![webmaker-postcard-5x7in2](https://cloud.githubusercontent.com/assets/12228435/8466562/d199650c-2008-11e5-9d4d-3ad79a614ce7.jpg)

**Comment by KevZawacki** [comment]
Looks great! A thought: the em dash looks a bit strange at the end of the first line. Maybe we replace it with a period?

"Download Webmaker for Android.
It's free and open source. --> webmaker.org"

**Comment by lovegushwa** [comment]
Good call @KevZawacki will do.

**Comment by edrushka** [comment]
Sounds like we're changing the poster to the 3-phone version, which should be reflected on the front of this card as well.

**Comment by lovegushwa** [comment]
Hi @edrushka discussed it with @cassiemc we are going to stick with 1 image for the card, 3 will be a bit too much to squeeze in a card (and the other screens have much smaller text elements.)

**Comment by edrushka** [comment]
Makes sense! Thanks.

**Comment by lovegushwa** [comment]
@cassiemc @xmatthewx  R?
Planning on sending these to the printer tonight if they are good to go.
You can check out the other language versions here:
https://github.com/mozilla/webmaker-launch/issues/47
https://github.com/mozilla/webmaker-launch/issues/80
https://github.com/mozilla/webmaker-launch/issues/79

![webmaker-postcard-5x7in-proof](https://cloud.githubusercontent.com/assets/12228435/8532840/ee499344-23e5-11e5-9985-09e23ffd50c4.jpg)
![webmaker-postcard-5x7in-proof2](https://cloud.githubusercontent.com/assets/12228435/8532839/ee47e3e6-23e5-11e5-8e12-ee4dd237a380.jpg)

**Comment by xmatthewx** [comment]
Nice. Let's block the tinker icon in the screen on the right. Destination tinker doesn't exist yet.

**Comment by lovegushwa** [comment]
Awesome, thanks @xmatthewx , will do!
